#!/bin/sh
#
# We take variables directly from others

audiofile_libs="`audiofile-config --libs`"
audiofile_cflags="`audiofile-config --cflags`"

gtk_libs="`pkg-config gtk+-2.0 --libs`"
gtk_cflags="`pkg-config gtk+-2.0 --cflags`"

glib_libs="`pkg-config glib-2.0 --libs`"
glib_cflags="`pkg-config glib-2.0 --cflags`"

esd_libs="`esd-config --libs`"

prefix=/usr
exec_prefix=/usr
exec_prefix_set=no

usage="\
Usage: libapril-config [--prefix[=DIR]] [--exec-prefix[=DIR]] [--version] [--libs] [--cflags]"

if test $# -eq 0; then
      echo "${usage}" 1>&2
      exit 1
fi

while test $# -gt 0; do
  case "$1" in
  -*=*) optarg=`echo "$1" | sed 's/[-_a-zA-Z0-9]*=//'` ;;
  *) optarg= ;;
  esac

  case $1 in
    --prefix=*)
      prefix=$optarg
      if test $exec_prefix_set = no ; then
        exec_prefix=$optarg
      fi
      ;;
    --prefix)
      echo $prefix
      ;;
    --exec-prefix=*)
      exec_prefix=$optarg
      exec_prefix_set=yes
      ;;
    --exec-prefix)
      echo $exec_prefix
      ;;
    --version)
      echo 1.0.0
      ;;
    --cflags)
      echo $gtk_cflags $glib_cflags 
      ;;
    --libs)
      libdirs=-L/usr/lib
      echo $libdirs $gtk_libs $glib_libs $esd_libs -lapril
      ;;
    *)
      echo "${usage}" 1>&2
      exit 1
      ;;
  esac
  shift
done
